plugins {
    id 'java'
    alias(libs.plugins.springBoot)
    alias(libs.plugins.springDependencyManagement)
}

description = 'Image Storage Worker - Manages image uploads to R2 (Cloudflare)'

dependencies {
    implementation project(':core:gallery')
    // AWS SDK v2 for R2 compatibility
    implementation(platform(libs.aws.bom))
    implementation(libs.aws.s3)       // S3Client + S3Presigner
    implementation(libs.aws.auth)      // AwsCredentialsProvider

    // Procesamiento de imágenes
    implementation(libs.thumbnailator)
    implementation(libs.metadata.extractor)


    // Monitoring
    implementation libs.spring.boot.starter.actuator
    implementation libs.micrometer.new.relic

    // Logging
    implementation libs.spring.boot.starter.logging

    // Lombok
    compileOnly libs.lombok
    annotationProcessor libs.lombok

    // Development

    // Testing
    testImplementation libs.spring.boot.starter.test
    testImplementation libs.reactor.test
    testImplementation libs.mockito.inline
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok
    testRuntimeOnly libs.junit.platform.launcher
}


jar {
    enabled = false
}