services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: our_place
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}

      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}

      R2_ENDPOINT: ${R2_ENDPOINT}
      R2_ACCESS_KEY: ${R2_ACCESS_KEY}
      R2_SECRET_KEY: ${R2_SECRET_KEY}
      R2_ACCOUNT_ID: ${R2_ACCOUNT_ID}
      R2_BUCKET: ${R2_BUCKET:-our-place-media}

      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      NEW_RELIC_LOG_LEVEL: ${NEW_RELIC_LOG_LEVEL:-info}
      NEWRELIC_ACCOUNT_ID: ${NEWRELIC_ACCOUNT_ID}

      FRONTEND_URL_DEV: ${FRONTEND_URL_DEV}

    restart: unless-stopped

