package org.our_place.map.api.event;


import org.our_place.common.shared.SharedDomain;
import org.our_place.shared.application.events.DomainEvent;
import org.our_place.shared.application.events.EventScope;

import java.time.Instant;
import java.util.UUID;

@SharedDomain(description = "Evento publicado cuando se crea un SavedPlace")
public record SavedPlaceCreatedEvent(
        UUID placeId,
        UUID roomId,
        UUID userId,
        boolean isAutogenerated

) implements DomainEvent {
    @Override
    public UUID eventId() {
        return UUID.randomUUID();
    }

    @Override
    public Instant occurredAt() {
        return Instant.now();
    }

    @Override
    public String key() {
        return "saved_place.created";
    }

    @Override
    public EventScope scope() {
        return EventScope.BOTH;
    }
}
