package org.our_place.map.service.dto;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

public record SavedPlaceDto(
        UUID id,
        UUID roomId,
        UUID createdByUserId,
        String categoryCode,
        String categoryName,
        String categoryIconUrl,
        String name,
        String description,
        String locationWkt,
        boolean isAutoGenerated,
        UUID sourceMediaId,
        LocalDate visitedAt,
        OffsetDateTime createdAt
) {}