plugins {
    id 'java'
    alias(libs.plugins.springBoot)
    alias(libs.plugins.springDependencyManagement)
}

description = 'Email Worker - Sends transactional emails (welcome, invoices, password reset, etc.)'

dependencies {
    // Envío de correo (SMTP) + motor de plantillas para el HTML del email
    implementation libs.spring.boot.starter.mail
    implementation libs.spring.boot.starter.thymeleaf
    
    // Monitoreo
    implementation libs.spring.boot.starter.actuator
    implementation libs.micrometer.new.relic

    // Lombok
    compileOnly libs.lombok
    annotationProcessor libs.lombok

    // Development
    //    developmentOnly libs.spring.boot.devtools

    // Testing
    testImplementation libs.spring.boot.starter.test
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok
    testRuntimeOnly libs.junit.platform.launcher
}

bootJar {
    mainClass = 'org.our_place.EmailWorkerApplication'
}

jar {
    enabled = false
}