spring:
  application:
    name: our-place-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

management:
  newrelic:
    metrics:
      export:
        enabled: false
        api-key: ${NEW_RELIC_LICENSE_KEY}
        account-id: ${NEWRELIC_ACCOUNT_ID}
        step: 30s
        meter-name-event-type-enabled: true
  metrics:
    tags:
      application: ${spring.application.name}