# New Relic configuration
management:
  newrelic:
    metrics:
      export:
        enabled: true
        api-key: ${NEW_RELIC_LICENSE_KEY}
        account-id: ${NEWRELIC_ACCOUNT_ID}
        step: 30s
        meter-name-event-type-enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

# datasource
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  #Aplicacion
  application:
    name: our-place-backend
