spring:
  application:
    name: our-place-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
  cloud:
    aws:
      s3:
        endpoint: ${R2_ENDPOINT}
      credentials:
        access-key: ${R2_ACCESS_KEY}
        secret-key: ${R2_SECRET_KEY}
      region: auto
management:
  newrelic:
    metrics:
      export:
        enabled: false
        api-key: ${NEW_RELIC_LICENSE_KEY}
        account-id: ${NEWRELIC_ACCOUNT_ID}
        step: 30s
        meter-name-event-type-enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration-ms: 3600000 # 1 hour
      refresh-expiration-ms: 156400000     # 43 days

#R2
r2:
  account-id: ${R2_ACCOUNT_ID}
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  bucket: ${R2_BUCKET:our-place-media}