plugins {
    alias(libs.plugins.springBoot)
    alias(libs.plugins.springDependencyManagement)
}

description = 'Main Application - Entry point for the Our Place backend services'

dependencies {
    // propias
    implementation project(':core:common')
    implementation project(':core:affection')
    implementation project(':core:billing')
    implementation project(':core:calendar')
    implementation project(':core:gallery')
    implementation project(':core:identity')
    implementation project(':core:map')
    implementation project(':core:notification')
    implementation project(':core:pet')
    implementation project(':core:room')
    implementation project(':shared')
    // Lo específico de emitir/validar JWT — SOLO identity lo necesita
    implementation libs.jjwt.api
    runtimeOnly libs.jjwt.impl
    runtimeOnly libs.jjwt.jackson
    implementation libs.spring.security.crypto
    implementation libs.spring.data.envers
}

bootJar {
    mainClass = 'org.our_place.ourplacebackend.OurPlaceBackendApplication'
}

jar {
    enabled = false
}

