package org.our_place.map.persistence.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "saved_place", schema = "map")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class SavedPlace {

    /** UUID: ubicaciones/direcciones privadas, evita enumeración entre salas. */
    @Id
    @Column(name = "id", nullable = false)
    private UUID id;

    /** Sin FK real: referencia lógica cross-schema a room.rooms.id. */
    @Column(name = "room_id", nullable = false)
    private UUID roomId;

    /** Sin FK real: referencia lógica cross-schema a identity.users_login.id. */
    @Column(name = "created_by_user_id", nullable = false)
    private UUID createdByUserId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_code", referencedColumnName = "code")
    private LkpPlaceCategory category;

    @Column(name = "name", length = 150, nullable = false)
    private String name;

    @Column(name = "description", columnDefinition = "text")
    private String description;

    /** Tipo geography de PostGIS; se mapea como texto (WKT) a nivel de entidad. */
    @Column(name = "location", nullable = false, columnDefinition = "geography")
    private String location;

    /** true si se creó desde el EXIF de una foto; false si fue manual. */
    @Column(name = "is_auto_generated", nullable = false)
    private boolean isAutoGenerated = false;

    /** Sin FK real: referencia lógica cross-schema a gallery.media.id. Puede quedar huérfano si la foto se purga. */
    @Column(name = "source_media_id")
    private UUID sourceMediaId;

    @Column(name = "visited_at")
    private LocalDate visitedAt;

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;
}
