package org.our_place.map.persistence.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.ColumnTransformer;
import org.springframework.data.domain.Persistable;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "saved_place", schema = "map")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class SavedPlace implements Persistable<UUID> {

    /**
     * UUID: ubicaciones/direcciones privadas, evita enumeración entre salas.
     */
    @Id
    @Column(name = "id", nullable = false)
    private UUID id;

    /**
     * Sin FK real: referencia lógica cross-schema a room.rooms.id.
     */
    @Column(name = "room_id", nullable = false)
    private UUID roomId;

    /**
     * Sin FK real: referencia lógica cross-schema a identity.users_login.id.
     */
    @Column(name = "created_by_user_id", nullable = false)
    private UUID createdByUserId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_code", referencedColumnName = "code")
    private LkpPlaceCategory category;

    @Column(name = "name", length = 150, nullable = false)
    private String name;

    @Column(name = "description", columnDefinition = "text")
    private String description;

    /**
     * Tipo geography de PostGIS; se mapea como texto (WKT) a nivel de entidad.
     */
    @ColumnTransformer(read = "ST_AsText(location)", write = "ST_GeogFromText(?)")
    @Column(name = "location", columnDefinition = "geography")
    private String location;

    /**
     * true si se creó desde el EXIF de una foto; false si fue manual.
     */
    @Column(name = "is_auto_generated", nullable = false)
    private boolean isAutoGenerated = false;

    /**
     * Sin FK real: referencia lógica cross-schema a gallery.media.id. Puede quedar huérfano si la foto se purga.
     */
    @Column(name = "source_media_id")
    private UUID sourceMediaId;

    @Column(name = "visited_at")
    private LocalDate visitedAt;

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    @Transient
    private boolean isNew = false;

    /**
     * Único punto de construcción válida de un SavedPlace (sección 6 de ModuleConventions.md).
     * Sirve tanto para creación manual (isAutoGenerated = false, sourceMediaId = null) como
     * para creación automática desde EXIF (isAutoGenerated = true, sourceMediaId presente).
     */
    public static SavedPlace create(
            UUID roomId,
            UUID createdByUserId,
            LkpPlaceCategory category,
            String name,
            String description,
            String locationWkt,
            boolean isAutoGenerated,
            UUID sourceMediaId,
            LocalDate visitedAt
    ) {
        SavedPlace place = new SavedPlace();
        place.id = UUID.randomUUID();
        place.isNew = true;
        place.roomId = roomId;
        place.createdByUserId = createdByUserId;
        place.category = category;
        place.name = name;
        place.description = description;
        place.location = locationWkt;
        place.isAutoGenerated = isAutoGenerated;
        place.sourceMediaId = sourceMediaId;
        place.visitedAt = visitedAt;
        place.createdAt = OffsetDateTime.now();
        return place;
    }

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PostPersist
    @PostLoad
    void markNotNew() {
        this.isNew = false;
    }
}