plugins {
    id 'java'
    alias(libs.plugins.springBoot)
    alias(libs.plugins.springDependencyManagement)
}

description = 'Room Service - Manage CRUD operations for rooms, including availability, pricing, and reservations'

dependencies {
    // Módulo transversal (JwtAuthenticationFilter, PublicEndpoints, AuthenticatedUser, etc.)
    implementation project(':core:common')

}