plugins {
    id 'java'
    alias(libs.plugins.springBoot)
    alias(libs.plugins.springDependencyManagement)
}

description = 'Calendar Service - Manages events, scheduling, and calendar operations'

dependencies {
    // DateTime handling (Calendar-specific)
    implementation project(':core:common')
    implementation project(':core:identity')
    implementation project(':shared')
    // extra
    implementation project(':core:gallery')

    implementation libs.joda.time
    implementation libs.jackson.datatype.jsr310

    // REST API support
//    implementation libs.spring.boot.starter.data.rest
}

jar {
    enabled = false
}