package org.our_place.map.controller.response;

import org.our_place.map.service.dto.SavedPlaceDto;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

public record SavedPlaceResponse(
        UUID id,
        UUID roomId,
        UUID createdByUserId,
        String categoryCode,
        String categoryName,
        String categoryIconUrl,
        String name,
        String description,
        String locationWkt,
        boolean isAutoGenerated,
        UUID sourceMediaId,
        LocalDate visitedAt,
        OffsetDateTime createdAt
) {
    public static SavedPlaceResponse from(SavedPlaceDto dto) {
        return new SavedPlaceResponse(
                dto.id(),
                dto.roomId(),
                dto.createdByUserId(),
                dto.categoryCode(),
                dto.categoryName(),
                dto.categoryIconUrl(),
                dto.name(),
                dto.description(),
                dto.locationWkt(),
                dto.isAutoGenerated(),
                dto.sourceMediaId(),
                dto.visitedAt(),
                dto.createdAt()
        );
    }
}
