plugins {
    id 'java'
    alias(libs.plugins.springBoot)
    alias(libs.plugins.springDependencyManagement)
}

description = 'Gallery Service - manage read operation to the gallery (images, videos, etc.)'

dependencies {
    // Módulo transversal (JwtAuthenticationFilter, PublicEndpoints, AuthenticatedUser, etc.)
    implementation project(':core:common')
}