package org.our_place.map.usecase.command;

import java.time.LocalDate;
import java.util.UUID;

public record CreateSavedPlaceCommand(
        UUID roomId,
        UUID createdByUserId,
        String categoryCode,
        String name,
        String description,
        String locationWkt,
        boolean isAutoGenerated,
        UUID sourceMediaId,
        LocalDate visitedAt
) {
}