package org.our_place.map.usecase;

import lombok.RequiredArgsConstructor;
import org.our_place.map.api.event.SavedPlaceCreatedEvent;
import org.our_place.map.domain.exception.PlaceCategoryNotFoundException;
import org.our_place.map.persistence.entity.LkpPlaceCategory;
import org.our_place.map.persistence.entity.SavedPlace;
import org.our_place.map.persistence.repository.LkpPlaceCategoryRepository;
import org.our_place.map.persistence.repository.SavedPlaceRepository;
import org.our_place.map.usecase.command.CreateSavedPlaceCommand;
import org.our_place.map.usecase.outout.CreateSavedPlaceOutput;
import org.our_place.shared.application.bus.EventBus;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;


@Component
@RequiredArgsConstructor
public class CreateSavedPlaceUseCase implements UseCase<CreateSavedPlaceCommand, CreateSavedPlaceOutput> {

    private final SavedPlaceRepository savedPlaceRepository;
    private final LkpPlaceCategoryRepository categoryRepository;
    private final EventBus eventBus;

    @Override
    @Transactional
    public CreateSavedPlaceOutput execute(CreateSavedPlaceCommand command) {
        LkpPlaceCategory category = categoryRepository.findById(command.categoryCode())
                .orElseThrow(() -> new PlaceCategoryNotFoundException(command.categoryCode()));

        SavedPlace place = SavedPlace.create(
                command.roomId(),
                command.createdByUserId(),
                category,
                command.name(),
                command.description(),
                command.locationWkt(),
                command.isAutoGenerated(),
                command.sourceMediaId(),
                command.visitedAt()
        );

        savedPlaceRepository.save(place);

        eventBus.publish(new SavedPlaceCreatedEvent(
                place.getId(),
                place.getRoomId(),
                place.getCreatedByUserId(),
                place.isAutoGenerated()
        ));

        return new CreateSavedPlaceOutput(
                place.getId(),
                place.getRoomId(),
                category.getCode(),
                place.getName(),
                place.getCreatedAt()
        );
    }
}