package org.our_place.map.service.mapper;


import org.our_place.map.persistence.entity.LkpPlaceCategory;
import org.our_place.map.persistence.entity.LocationPing;
import org.our_place.map.persistence.entity.SavedPlace;
import org.our_place.map.service.dto.LocationPingDto;
import org.our_place.map.service.dto.PlaceCategoryDto;
import org.our_place.map.service.dto.SavedPlaceDto;

public final class MapMapper {

    private MapMapper() {}

    public static SavedPlaceDto toDto(SavedPlace place) {
        return new SavedPlaceDto(
                place.getId(),
                place.getRoomId(),
                place.getCreatedByUserId(),
                place.getCategory() != null ? place.getCategory().getCode() : null,
                place.getCategory() != null ? place.getCategory().getName() : null,
                place.getCategory() != null ? place.getCategory().getIconUrl() : null,
                place.getName(),
                place.getDescription(),
                place.getLocation(),
                place.isAutoGenerated(),
                place.getSourceMediaId(),
                place.getVisitedAt(),
                place.getCreatedAt()
        );
    }

    public static LocationPingDto toDto(LocationPing ping) {
        return new LocationPingDto(
                ping.getUserLoginId(),
                ping.getLocation(),
                ping.getBatteryLevel(),
                ping.getRecordedAt()
        );
    }

    public static PlaceCategoryDto toDto(LkpPlaceCategory category) {
        return new PlaceCategoryDto(
                category.getCode(),
                category.getName(),
                category.getIconUrl()
        );
    }
}